name: Deploy tldraw to GitHub Pages

on:
  push:
    branches: [ main ]  # 触发分支，按需修改

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写入 gh-pages 分支

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # tldraw 要求 Node 16+

      # 3. 安装依赖并构建
      - name: Install and Build
        run: |
          npm ci
          npm run build

      # 4. 部署到 GitHub Pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist  # tldraw 默认构建目录
          keep_files: false  # 清除旧文件